# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx1536m

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true

# AndroidX package structure to make it clearer which packages are bundled with the
# Android operating system, and which are packaged with your app's APK
# https://developer.android.com/topic/libraries/support-library/androidx-rn
android.useAndroidX=true

systemProp.http.proxyHost=21.0.0.151
systemProp.http.proxyPort=15004
systemProp.http.proxyUser=container_container_014HpTbUzZqL9h7LyYug2ZJp--claude_code_remote--26a883
systemProp.http.proxyPassword=jwt_eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6Iks3dlRfYUVsdXIySGdsYVJ0QWJ0UThDWDU4dFFqODZIRjJlX1VsSzZkNEEifQ.eyJpc3MiOiJhbnRocm9waWMtZWdyZXNzLWNvbnRyb2wiLCJvcmdhbml6YXRpb25fdXVpZCI6IjUzYmYyODJlLTliOTgtNDNmYy05NDU3LTY4ZjcxNWEyN2IyMyIsImlhdCI6MTc3MTY3MTk0NCwiZXhwIjoxNzcxNjg2MzQ0LCJhbGxvd2VkX2hvc3RzIjoiKiIsImlzX2hpcGFhX3JlZ3VsYXRlZCI6ImZhbHNlIiwiaXNfYW50X2hpcGkiOiJmYWxzZSIsInVzZV9lZ3Jlc3NfZ2F0ZXdheSI6InRydWUiLCJzZXNzaW9uX2lkIjoic2Vzc2lvbl8wMTNHNFJrQWNGNzRlaGhSOHZoV2tldTEiLCJjb250YWluZXJfaWQiOiJjb250YWluZXJfMDE0SHBUYlV6WnFMOWg3THlZdWcyWkpwLS1jbGF1ZGVfY29kZV9yZW1vdGUtLTI2YTg4MyJ9.vuq4iPxKNbuExd8v3pw6qBGA6wMAO00uovxKA2H2Pn4er4jlqAujQnuI7r554mH8zIfLwYlWnEu5PkkFYB0mkg
systemProp.http.nonProxyHosts=localhost|127.0.0.1|169.254.169.254|metadata.google.internal
systemProp.https.proxyHost=21.0.0.151
systemProp.https.proxyPort=15004
systemProp.https.proxyUser=container_container_014HpTbUzZqL9h7LyYug2ZJp--claude_code_remote--26a883
systemProp.https.proxyPassword=jwt_eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6Iks3dlRfYUVsdXIySGdsYVJ0QWJ0UThDWDU4dFFqODZIRjJlX1VsSzZkNEEifQ.eyJpc3MiOiJhbnRocm9waWMtZWdyZXNzLWNvbnRyb2wiLCJvcmdhbml6YXRpb25fdXVpZCI6IjUzYmYyODJlLTliOTgtNDNmYy05NDU3LTY4ZjcxNWEyN2IyMyIsImlhdCI6MTc3MTY3MTk0NCwiZXhwIjoxNzcxNjg2MzQ0LCJhbGxvd2VkX2hvc3RzIjoiKiIsImlzX2hpcGFhX3JlZ3VsYXRlZCI6ImZhbHNlIiwiaXNfYW50X2hpcGkiOiJmYWxzZSIsInVzZV9lZ3Jlc3NfZ2F0ZXdheSI6InRydWUiLCJzZXNzaW9uX2lkIjoic2Vzc2lvbl8wMTNHNFJrQWNGNzRlaGhSOHZoV2tldTEiLCJjb250YWluZXJfaWQiOiJjb250YWluZXJfMDE0SHBUYlV6WnFMOWg3THlZdWcyWkpwLS1jbGF1ZGVfY29kZV9yZW1vdGUtLTI2YTg4MyJ9.vuq4iPxKNbuExd8v3pw6qBGA6wMAO00uovxKA2H2Pn4er4jlqAujQnuI7r554mH8zIfLwYlWnEu5PkkFYB0mkg
systemProp.https.nonProxyHosts=localhost|127.0.0.1|169.254.169.254|metadata.google.internal
